### ISSUE TITLE
A request (idea)

### ISSUE THREAD

**Issue by SpartakusMd** [bellbind/altrefcontrol#1]
Hi.
Could you edit this addon and make it with settings window instead of right click menu. I think it would be awesome. Users don't need this option on every site, page... I think you shuld make something similar to the RefControl addon.

**Comment by bellbind** [comment]
Thank you for your advice. 

`content/refcontrol.uc.js` and `content/refcontrolui.uc.js` is completely independent, because of:
- `refcontrol.uc.js`: Hook requests to modify Referer header by the config values, and set observer to the config system.
- `refcontrolui.uc.js`: create menu to edit the config

The config "refcontrol.actions" (it is the same key of original refcontrol addon) can be  also edit from about;config UI.

You can easily remove the script tag of `refcontrolui.uc.js` from `content/loader.xul` and can add another UI for config editing.

**Comment by SpartakusMd** [comment]
I wish I could, but my I don't have the necesary knowledges to add UI.

**Comment by bellbind** [comment]
The table style option editor (launched from "add-ons manager" options button) added:
- https://dl.dropboxusercontent.com/u/14499563/altrefcontrol/altrefcontrol-0.2.8.xpi
